name: Formatting

on:
  pull_request:
    branches: [main]

jobs:
  black:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable


  isort:
    name: Isort Import Sorter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@master
  
